#!/bin/bash -x

rm /var/tmp/lmc-work-* -rf
if [ ! -e CentOS-8.4.2105-x86_64-dvd1.iso ]; then
    wget http://ftp.osuosl.org/pub/centos/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso
fi
livemedia-creator --ks fdi-image.ks --make-iso --nomacboot --iso CentOS-8.4.2105-x86_64-dvd1.iso
cp /var/tmp/lmc-work-*/images/boot.iso .
du -h boot.iso
exit 0
