FROM centos:7

RUN yum install -y pykickstart isomd5sum syslinux grub2-efi shim grub2-efi-x64 grub2-efi-x64-cdboot shim-x64 git libguestfs-tools dd mkisofs isohybrid implantisomd5
RUN rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
RUN yum install -y https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
RUN yum install -y livecd-tools
RUN git clone https://github.com/theforeman/foreman-discovery-image.git
RUN (cd foreman-discovery-image; ./build-livecd fdi-centos7.ks)
#RUN (cd foreman-discovery-image; ./build-livecd-root)
