# vim: sw=2:ts=2:et:ft=ruby

boxes = [
  {:name => 'f27', :libvirt => 'fedora/27-cloud-base', :image_name => /Fedora 27/, :pty => true},
  {:name => 'f28', :libvirt => 'fedora/28-cloud-base', :image_name => /Fedora 28/, :pty => true},
  {:name => 'el6', :libvirt => 'centos/6',             :image_name => /CentOS 6/,  :pty => true},
  {:name => 'el7', :libvirt => 'centos/7',             :image_name => /CentOS 7/,  :pty => true, :default => true},
]

if ENV['box']
  boxes << {:name => ENV['box'], :libvirt => ENV['box'], :image_name => ENV['box']}
end

SHELLARGS = []
SHELLARGS << ENV['repoowner'] || ''
SHELLARGS << ENV['branch'] || ''
SHELLARGS << ENV['proxy_repo'] || ''

Vagrant.configure("2") do |config|
  boxes.each do |box|
    config.vm.define box[:name], primary: box[:default] do |machine|
      machine.vm.box = box[:name]
      machine.vm.hostname = "foreman-#{box[:name]}.imagebuilderv2.theforeman.org"
      machine.vm.provision :shell, :path => 'build_image.sh', :args => SHELLARGS

      machine.vm.provider :libvirt do |p, override|
        override.vm.box = box[:libvirt]
        p.memory = 1024
      end

      config.vm.provider :openstack do |p, override|
        override.vm.box = 'dummy'
        p.server_name   = machine.vm.hostname
        p.flavor        = /m1.tiny/
        p.image         = box[:image_name]

        # ~/.vagrant.d/Vagrantfile will need
        # p.username     = "admin"                             # e.g. "#{ENV['OS_USERNAME']}"
        # p.api_key      = "secret"                            # e.g. "#{ENV['OS_PASSWORD']}"
        # p.endpoint     = "http://openstack:5000/v2.0/tokens" # e.g. "#{ENV['OS_AUTH_URL']}/tokens"
        # p.keypair_name = "my_key"                            # as stored in Nova

        # You may need
        # p.floating_ip = '172.20.10.160' # Must be hardcoded, cannot ask Openstack for an IP
      end
    end
  end
end
