# vim: sw=2:ts=2:et:ft=ruby

SHELLARGS = []
SHELLARGS << (ENV['repoowner'] || '')
SHELLARGS << (ENV['branch'] || '')
SHELLARGS << (ENV['proxy_repo'] || '')

Vagrant.configure("2") do |config|
  config.ssh.username  = "root"
  config.ssh.pty = true

  config.vm.define "el7", primary: true do |machine|
    machine.vm.hostname = "fdi-builder-vm"
    machine.vm.provision :shell, :path => 'build_image.sh', :args => SHELLARGS

    config.vm.provider :libvirt do |lv, cfg|
      cfg.ssh.username = "vagrant"
      lv.server_name = machine.vm.hostname
      lv.vm.box = "centos/7"
      lv.memory = 1024
    end

    # openstack needs credentials in ~/.vagrant.d/Vagrantfile
    config.vm.provider :openstack do |os, override|
      os.server_name = machine.vm.hostname
      os.flavor = /4GB/
      os.image = /CentOS 7.*PV/
    end
  end
end
