#!/bin/bash -x

[ "$1" != "chroot" ] && echo "Not to be used outside chroot" && exit 1

# permissions
chown -R root:root .

# copy root folders to the real root
cp -rvf /var/tmp/root/*/ /

# flags
chmod +x \
  /etc/rc.d/rc.local \
  /usr/bin/discover-host \
  /usr/bin/find-missing-libs \
  /usr/bin/find-largest-rpms

# cleanup
rm -rf /var/tmp/root/*
